name: Daily Job Checker

on:
  schedule:
    - cron: "0 13 * * *"  # 9am EST (13:00 UTC)
    - cron: "0 15 * * *"  # 11am EST (15:00 UTC)
    - cron: "0 17 * * *"  # 1pm EST (17:00 UTC)
    - cron: "0 19 * * *"  # 3pm EST (19:00 UTC)
  workflow_dispatch:

  push: 
    branches:
      - main

jobs:
  check-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.GH_TOKEN }}  # ✅ this ensures clone & push work

      - name: Configure Git
        run: |
            git config --global user.name "Ishan Phadte"
            git config --global user.email "ishanphadte@gmail.com"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run job checker
        run: python scripts/check_jobs.py
        env:
          EMAIL_FROM: ishanphadte@gmail.com
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      - name: Commit and push updated job data
        run: |
            curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/user
            git add data/previous_jobs.json
            if git diff --staged --quiet; then
            echo "No changes to commit."
            else
                git commit -m "Update job listings"
                git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/IshanPhadte776/JobPostingScrapper.git
                git push -u origin main
            fi 

        env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}