name: Daily Job Checker

on:
  schedule:
    - cron: "0 14 * * *"  # runs daily at 2 PM UTC
  workflow_dispatch:

  push: 
    branches:
      - main

jobs:
  check-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
            git config --global user.name "Ishan Phadte"
            git config --global user.email "ishanphadte@gmail.com"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          token: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies
        run: pip install requests

      - name: Run job checker
        run: python scripts/check_jobs.py
        env:
          EMAIL_FROM: ishanphadte@gmail.com
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      - name: Commit and push updated job data
        run: |
            curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/user
            git add data/previous_jobs.json
            git commit -m "Update job listings"
            git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/IshanPhadte776/JobPostingScrapper.git
            git push -u origin main

        env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}